### ISSUE TITLE
Can you provide installation package？

### ISSUE THREAD

**Issue by RioWong** [MEPP-team/MEPP2#27]
Can you provide installation package in different platform like windows, linux and mac？I think you could list the 3rd party library and least version in .md file so others can compile it correctly.Thank you.

**Comment by mtola** [comment]
Hello, thank you for your interest in MEPP2.

Please, read
https://github.com/MEPP-team/MEPP2/blob/master/Install.md
Everything is here.
**When there is a minimum version, this is specified.**

For Windows you have binary kit(s).
For Linux and Mac OS X obviously it depends of the kernel or the distribution/version of Linux/OS X and libraries/HomeBrew.

So, just read, follow the instructions and install. ;-) It works, tested under the 3 OS last month by me.

In addition, for the moment this software is a free research and education software delivered "as is" and not a commercial software: so for now, we have only that...

**Comment by RioWong** [comment]
Sorry for my careless，I ignore it yesterday."MEPP2_local_vs2015_64.7z"  binary kit is a runnable exe?I just want to have a try for my laptop with low-configuration,I don't want to compile them...

**Comment by mtola** [comment]
This file is a compressed archive in 7zip format (like .zip or .rar archives...) which contains a part (the first mandatory part exactly) of the binary kit for windows (headers, libraries and dlls...).

It is a dependency of MEPP2. So by definiton no .exe of MEPP2 inside.

Again, Install.md takes you by the hand if you take the time to read.
So please read it again, line by line, step by step and follow the procedure here:
https://github.com/MEPP-team/MEPP2/blob/master/Install.md

(You must clone the sources of MEPP2, install the desired binary modular kit parts, install Visual Studio, and compile MEPP2 from sources.)

**Comment by RioWong** [comment]
OK，I try to download it and compile.Thank you!
