### ISSUE TITLE
MSDM2 on non-manifold meshes

### ISSUE THREAD

**Issue by dcoeurjo** [MEPP-team/MEPP2#29]
Is MSDM2 supposed to work on non-manifold meshes ? 
The `example_msdm2` outputs a value on a pair non-manifold OBJs but it looks like the distance not make sense (e.g. computing on the same mesh returns ~0.2).

**Comment by glavoue** [comment]
No, MSDM2 only works on manifold meshes. It relies on curvature computation, which needs a proper connectivity.

**Comment by dcoeurjo** [comment]
👌
I was aware of the multiscale curvature map but as the tool accepted the non-manifold files, I suspected there was an update on that (like extrinsic curvature or so)
Thx for the feedback.
