### ISSUE TITLE
Curvature

### ISSUE THREAD

**Issue by aadha3** [MEPP-team/MEPP2#31]
Hello,
Thank you for the repository. I am using curvature plugin to identify the chains(1-ring) in the 3D models.It worked well for the  below example.
![firstexample](https://user-images.githubusercontent.com/27354209/114709932-752e7480-9d2d-11eb-899a-f0a46a934a38.png)
However when I used the same parameters and used the same plugin for some more examples I couldn't see the curvature results(colormap).Please find the below example.
![secondexample](https://user-images.githubusercontent.com/27354209/114710082-9ee79b80-9d2d-11eb-8c65-f3995469c274.png)
Is there anything I am missing or what could be the reason behind it?
Thank you very much

**Comment by glavoue** [comment]
Hi, in the results below, the difference with above is just that your range of curvature is larger (you probably have tiny regions somewhere where the curvature is very high) ; consequently, most of vertices of low to medium curvature are in blue. 
You can increase the "curvature radius" to improve the results (make sure that you use the "Geodesic" parameter).

**Comment by aadha3** [comment]
Hello,
I am trying to identify the vertices which are a part of a ring(circular chain) with around same kind of curvature. I tried the curvature plugin with 1- ring and it identified those kind of  vertices which forms a circle.Please find the below images
![githubupload](https://user-images.githubusercontent.com/27354209/115300911-d35dbc00-a160-11eb-8987-33f551316dbc.png)
Is there a way I could identify the vertices that are lying on the circle with the help of curvature(min and max curvature)
Thank you very much

**Comment by glavoue** [comment]
Hi,
A simple K-means clustering should do the job. E.g., see section 4.4.2 from this paper https://perso.liris.cnrs.fr/guillaume.lavoue/travaux/revue/scienceCAD.pdf
