### ISSUE TITLE
Seg fautl on example_msdn2

### ISSUE THREAD

**Issue by simogasp** [MEPP-team/MEPP2#32]
Hi, we are trying to compare two meshes using `example_msdn2`.
We get a segmentation fault around these lines in `curvature.hpp` , function `geodes_principal_curvature_per_vert`
```c++
    do
    {
      const Point3d p1 = get(pm, target(*h, g));   // here
      const Point3d p2 = get(pm, source(*h, g));

```
Apparently, the out-of-index or empty access comes from `target()`. 
I attach here the two meshes that we are testing.

The "degraded" mesh (pumpkin_hole_15_2.obj) has some holes we create to degrade the mesh. I don't know if that may be the problem. In that case, has the mesh to be watertight for the measure to be computed?

Thanks in advance for any help you can provide!
[Pumpkin Hole.zip](https://github.com/MEPP-team/MEPP2/files/6353942/Pumpkin.Hole.zip)

**Comment by glavoue** [comment]
Hi,
No need for the meshes to be watertight.
The problem comes from the fact that your "degraded" mesh has two isolated vertices. I removed them with meshlab and it works.
[pumpkin_hole_15_2.zip](https://github.com/MEPP-team/MEPP2/files/6374442/pumpkin_hole_15_2.zip)

**Comment by simogasp** [comment]
Thank you for your answer, there was indeed a problem on our side on how we generate the holes which sometimes can keep some isolated vertices.
