### ISSUE TITLE
Failed assertion missed due to Release mode

### ISSUE THREAD

**Issue by Aelphy** [MEPP-team/MEPP2#36]
https://github.com/MEPP-team/MEPP2/blob/f0651ed0874c3287ad1b3b0a113b83905c8dcc47/FEVV/Filters/Generic/mesh_from_vector_representation.hpp#L686

I have a mesh which fails the assertion above.
PR is comming

**Comment by elombardi2** [comment]
Fixed by [this commit](https://github.com/MEPP-team/MEPP2/commit/03189b999f2d4463793e8f10c045b7e26ce9d17e), inspired by [this PR](https://github.com/MEPP-team/MEPP2/pull/37).
