### ISSUE TITLE
Application Crashes Applying MSDM2 Metric

### ISSUE THREAD

**Issue by jacobfa** [MEPP-team/MEPP2#40]
Hello,
I am using the virtual machine provided in the website's installation guide. When I upload my meshes and apply the MSDM2 metric, the following error message is produced every time, and the application crashes. I would like to run this program properly but have no idea how a seg fault can help me fix this bug. Here is my complete error message:

```
####################################
# Begin block: Init Visualization. #
####################################
Gtk-Message: 22:09:38.827: Failed to load module "canberra-gtk-module"
####################################
# End block:   Init Visualization. #
# Elapsed time: 0.0496669s #
####################################
libpng warning: iCCP: known incorrect sRGB profile
Generic reading of "LRSTC_predicted.obj"
read_mesh(): found vertex color with size != 3. Disabling vertex color for all vertices.
read_mesh(): 1752 vertices duplicated (non-manifold mesh).
read_mesh(): the mesh has 6181 vertices, 14113 edges, 7561 faces.
Generic reading of "LRSTC_predicted.obj" done in 0.0100784s (parsing 0.00664439s, populating DS 0.00343401s).
libpng warning: iCCP: known incorrect sRGB profile
SimpleViewer init
[SimpleViewer] face normal missing, computing it
[SimpleViewer] vertex normal missing, computing it
[SimpleViewer] no material found, disabling textures
[SimpleViewer] I have drawn 7561 faces (with 22683 vertices).
[SimpleViewer] I have also drawn 6181 (superimpose) points and 14113 superimpose lines.
[MeshLoading] Loading using legacy rendering.
geometry.setUseVertexBufferObjects(1)
geometry.setUseDisplayList(0)
[SimpleViewer] Done 'loading' mesh (in graphic card) in 0.00153008 seconds.
[SimpleViewer] mesh 0x562b11c91ff0 stored with datastructure SURFACEMESH
Generic reading of "true.obj"
read_mesh(): found vertex color with size != 3. Disabling vertex color for all vertices.
read_mesh(): 588 vertices duplicated (non-manifold mesh).
read_mesh(): the mesh has 3216 vertices, 7007 edges, 3964 faces.
Generic reading of "true.obj" done in 0.00537146s (parsing 0.00375572s, populating DS 0.00161574s).
[SimpleViewer] face normal missing, computing it
[SimpleViewer] vertex normal missing, computing it
[SimpleViewer] no material found, disabling textures
[SimpleViewer] I have drawn 3964 faces (with 11892 vertices).
[SimpleViewer] I have also drawn 3216 (superimpose) points and 7007 superimpose lines.
[MeshLoading] Loading using legacy rendering.
geometry.setUseVertexBufferObjects(1)
geometry.setUseDisplayList(0)
[SimpleViewer] Done 'loading' mesh (in graphic card) in 0.00165916 seconds.
[SimpleViewer] mesh 0x562b126f95c0 stored with datastructure SURFACEMESH
Applying filter
use existing face-normal map for degraded mesh
use existing face-normal map for original mesh
Asking to calculate curvature
Segmentation fault (core dumped)
```

**Comment by elombardi2** [comment]
Could you please attach the two meshes to the issue?

**Comment by jacobfa** [comment]
Github does not allow me to attach .obj files so I have added a Mediafire link
https://www.mediafire.com/folder/vh6vfnwigc8xf/Meshes

**Comment by elombardi2** [comment]
[Here](https://github.com/MEPP-team/MEPP2/files/9160480/random_meshes.zip) are the two meshes.

And a view of them:
![Capture d’écran du 2022-07-21 16-09-04](https://user-images.githubusercontent.com/11190899/180249438-72d969b5-fc11-40af-a8bb-219474e7b50c.png)

**Comment by jacobfa** [comment]
> [Here](https://github.com/MEPP-team/MEPP2/files/9160480/random_meshes.zip) are the two meshes.
> 
> And a view of them: ![Capture d’écran du 2022-07-21 16-09-04](https://user-images.githubusercontent.com/11190899/180249438-72d969b5-fc11-40af-a8bb-219474e7b50c.png)

Yes, these two meshes look quite ridiculous I am aware. The actual data I am working with is confidential and I am not able to provide it to you. I uploaded these two meshes because applying the MSDM2 metric on any two meshes I have tried crashes the application. I would like to see how I can use this metric correctly using this program.

**Comment by elombardi2** [comment]
You can test MSDM2 metric with the [monkey.obj](https://github.com/MEPP-team/MEPP2/blob/67cea3ffe43882eef710abcc66558d6fba65fe7c/Testing/Data/monkey.obj) and the [monkey_simplified.obj](https://github.com/MEPP-team/MEPP2/blob/67cea3ffe43882eef710abcc66558d6fba65fe7c/Testing/Data/monkey_simplified.obj) meshes, provided in the `MEPP2/Testing/Data` directory.

Input:

![](https://user-images.githubusercontent.com/11190899/181170084-266413cc-c4e9-49fd-8cfe-5961e13559aa.png)

Output:

![](https://user-images.githubusercontent.com/11190899/181170116-8df2f062-bc9d-4318-acbc-847d3e3bbe12.png)

The MSDM2 score is visible in the console:

![](https://user-images.githubusercontent.com/11190899/181170177-f1f0c463-fade-4b7d-bbd9-f8b5e4b94264.png)

**Comment by elombardi2** [comment]
MSDM2 metric relies on computing the curvature at vertices. If the mesh has some geometric aberration (zero-area face, isolated vertex, isolated edge), the curvature computation may crash. That's probably what happens in your case.
